services:
  weaviate:
    image: semitechnologies/weaviate:1.39.3-2489571.amd64
    ports:
      - "8084:8080"
      - "50051:50051"
    restart: on-failure:0
    volumes:
      - "./datasets/weaviate:/var/lib/weaviate"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      DEFAULT_VECTORIZER_MODULE: "none"
      CLUSTER_HOSTNAME: "node1"


  graphdb:
    image: khaller/graphdb-free:10.6.2
    container_name: graphdb
    restart: unless-stopped

    ports:
      - "7200:7200"          # SPARQL endpoint + UI

    environment:
      GDB_HEAP_SIZE: 2G      # adjust for your RAM

    volumes:
      - ./datasets/graphdb:/opt/graphdb/home
      - ./repository.init:/repository.init

    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:7200/rest/monitor/health"]
      interval: 10s
      timeout: 5s
      retries: 30

  fastapi:
    build: ./fastapi
    container_name: sparql_api
    ports:
      - "8000:8000"
    environment:
      OLLAMA_BASE_URL: http://10.42.0.192:11434
      GEN_MODEL: gpt-oss:20b
 

  worker-agent:
    build: ./worker-agent
    container_name: worker_agent
    ports:
      - "8001:8000"
    shm_size: '2gb'
    environment:
      OLLAMA_URL: http://10.42.0.192:11434
      GEN_MODEL: ornith:9b 
      DISTILL_GEN_MODEL: granite4.1:8b 
      WORKSPACE: /agentworkspace
    volumes:
      - ./worker-agent:/app
      - ./worker-agent-workspace:/agentworkspace
    restart: unless-stopped

  validator-agent:
    build: ./validator-agent
    container_name: validator_agent
    ports:
      - "8002:8000"
    environment:
      OLLAMA_URL: http://10.42.0.192:11434
      GEN_MODEL: gpt-oss:20b
    restart: unless-stopped
