{
 "title": "Agent Metrics",
 "description": "Overview of agent actions",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Worker Tokens in play",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{__name__=~\"worker_agent.*play\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Worker Agent Metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "{__name__=~\"worker_agent_operation.*total\"}",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "{__name__=\"worker_agent_tool_call_total\"}",
     "legendFormat": "{{tool_call}}"
    },
    {
     "expr": "{__name__=\"worker_agent_tool_call_failure_total\"}",
     "legendFormat": "{{failure}}"
    }
   ]
  },
  {
   "title": "Validator Agent Metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "{__name__=~\"validator_agent_operation.*total\"}",
     "legendFormat": "{{operation}}"
    },
    {
     "expr": "{__name__=\"validator_agent_support_total\"}",
     "legendFormat": "{{support}}"
    },
    {
     "expr": "{__name__=\"worker_agent_error_total\"}",
     "legendFormat": "{{failure}}"
    }
   ]
  }
 ]
}